[package]
name = "welltemplate"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.1"
egui = "0.32.1"
open = "5.3.2"
rfd = "0.15.4"
image = "0.25.5"
anyhow = "1.0.101"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
itertools = "0.14.0"
